version: '3'
services:
  debotracy:
    container_name: debotracy
    build:
      context: .
      dockerfile: Dockerfile
    image: result/latest
    # image: ghcr.io/latoufff/debotracy:main
    env_file:
      - .env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  
  debotracy-db:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

volumes:
  db: