version: '3'
services:
  discord-bot:
    container_name: discord-bot
    image: ghcr.io/latoufff/debotracy:main
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure